ATTR_ALL_ZONE_DETECTION_DICT = 'allZoneDetectionDict'
ATTR_FAILURE = 'failure'
ATTR_ABNORMAL = 'abnormal'
ATTR_SWITCH_ID_LIST = 'switchIDList'
ATTR_SERVER_ID_LIST = 'serverIDList'
ATTR_LINK_ID_LIST = 'linkIDList'

ATTR_QUERY_TYPE = 'query_type'
ATTR_METRIC_NAME = 'metric_name'
ATTR_ZONE = 'zone'
ATTR_TIME_WINDOW = 'time_window_datapoints_num'
ATTR_INSTANCE_TYPE = 'instance_type'
ATTR_INSTANCE_ID_LIST = 'instance_id_list'

INSTANCE_TYPE_SWITCH = 'switches'
INSTANCE_TYPE_LINK = 'links'
INSTANCE_TYPE_SERVER = 'servers'
INSTANCE_TYPE_SFCI = 'sfcis'
INSTANCE_TYPE_VNFI = 'vnfis'

QUERY_TYPE_HISTORY = 'history_value'
QUERY_TYPE_ANOMALY = 'anomaly_record'
QUERY_TYPE_FAILURE = 'failure_record'
QUERY_TYPE_INSTANCE_ID = 'instance_id_list'

ATTR_ACTIVE = 'Active'
ATTR_TIMESTAMP = 'timestamp'
ATTR_SERVER = 'server'
ATTR_SWITCH = 'switch'
ATTR_LINK = 'link'
ATTR_VNFI = 'vnfi'
ATTR_SFCI = 'sfci'
ATTR_VALUE = 'value'