METRIC = 'metric'
VALUE = 'value'
LAST = 'last_timestamp'
CURRENT = 'current_timestamp'

ALL_ZONE_DETECTION_DICT = 'allZoneDetectionDict'
FAILURE = 'failure'
ABNORMAL = 'abnormal'
SWITCH_ID_LIST = 'switchIDList'
SERVER_ID_LIST = 'serverIDList'
LINK_ID_LIST = 'linkIDList'

UUID = 'uuid'
REPLY_TIMESTAMP = 'timestamp'
REPLY_QUERY_TYPE = 'query_type'
REPLY_INSTANCE_TYPE = 'instance_type'
REPLY_INSTANCE_ID = 'instance_id'

REQUEST_QUERY_TYPE_HISTORY_VALUE = 'history_value'
REQUEST_QUERY_TYPE_ANOMALY_RECORD = 'anomaly_record'
REQUEST_INSTANCE_TYPE_SWITCH = 'switch'
REQUEST_INSTANCE_TYPE_LINK = 'link'
REQUEST_INSTANCE_TYPE_SERVER = 'server'
